title: "Reghan Hesser" # your name (or website title) here
logo: "/images/headshot.jpg"
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br><br>
<a href='https://www.linkedin.com/in/reghan-hesser-8a2697205/'>LinkedIn</a>
  <br>
  <a href="/images/ReghanLynnHesserResume (1).pdf">Resume</a>
  <br>
  <a href='https://https://github.com/reghanhesser?tab=projects/'>GitHub</a>  
  <br>
  <a href='https://www.instagram.com/reghanhesser/'>Instagramr</a>  
  
  
theme: jekyll-theme-minimal
