title: "Reghan Hesser" # your name (or website title) here
logo: "/images/headshot.jpg"
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br><br>
<a href='https://www.linkedin.com/in/reghan-hesser-8a2697205/'>LinkedIn</a>
  <br>
  <a href="/images/ReghanLynnHesserResume (1).pdf">Resume</a>
  <br>
  <a href='https://bowen.finance/' class='btn btn--info'>Portfolio</a>  
  <br>
  <a href='https://www.GitHub.com/donbowen/'>GitHub</a>  
  <br>
  <a href='https://www.twitter.com/donbowen/'>Twitter</a>  
  <br>
  <a href='https://www.youtube.com/donbowen/'>Youtube</a>
  
theme: jekyll-theme-minimal
