title: "Reghan Hesser" # your name (or website title) here
logo: "<p style='text-align:center;'><img class='img-circle' src='https://github.com/reghanhesser/personal-website/raw/master/headshot.jpeg' width='100%'></p>"
description: > # your text below (remove <br> elements if you don't need line breaks)
  Edit these links below   
  <br>
  in _config.yml 
  <br><br>
  <a href='https://www.linkedin.com/in/reghan-hesser-8a2697205/'>LinkedIn</a>
  <br>
  <a href='https://bowen.finance/cv/' class='btn btn--info'>Resume</a>  
  <br>
  <a href='https://bowen.finance/' class='btn btn--info'>Portfolio</a>  
  <br>
  <a href='https://www.GitHub.com/donbowen/'>GitHub</a>  
  <br>
  <a href='https://www.twitter.com/donbowen/'>Twitter</a>  
  <br>
  <a href='https://www.youtube.com/donbowen/'>Youtube</a>
  
theme: jekyll-theme-minimal
